### ISSUE TITLE
README references nonexistent asset

### ISSUE THREAD

**Issue by segiddins** [KrauseFx/fastlane-plugin-clubmate#2]
https://raw.githubusercontent.com/fastlane/fastlane/master/fastlane/assets/plugin-badge.svg 404s

**Comment by KrauseFx** [comment]
Thanks for the issue, that's due to the not yet merged `pr-manager` branch, the asset will load successfully once we merged 👍 I'll leave this open to check back if everything works fine once we're at that point

**Comment by KrauseFx** [comment]
Fixed 👍
